### ISSUE TITLE
Consider `<label is="core-label">`

### ISSUE THREAD

**Issue by ssorallen** [googlearchive/core-label#2]
The `for` attribute logic in `core-label` reimplements native `<label for>` support but doesn't look like it needs to. The auto `aria-labelledby` attribute addition would be nice to keep by first searching this element's shadow DOM and then defaulting to the hosting document if no matching element with the `for` ID exists.

**Comment by ssorallen** [comment]
This is a try with native extension: https://github.com/Polymer/core-label/tree/extend-native-label
- All "for" focus/click/tap handling is removed and left to the native `<label>`

**Comment by gertcuykens** [comment]
+1 make it consistent with https://github.com/Polymer/paper-input/blob/master/paper-input-decorator.html 

```
    <paper-input-decorator>
        <label for="test" is="core-label">Test</label>
        <input id="test" is="core-input">
    </paper-input-decorator>
```
